package com.gzjy.user.model;

import java.util.Date;

public class Kaptchas {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaptchas.id
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaptchas.session_id
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaptchas.checkcode
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    private String checkcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kaptchas.expire_time
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    private Date expireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaptchas.id
     *
     * @return the value of kaptchas.id
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaptchas.id
     *
     * @param id the value for kaptchas.id
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaptchas.session_id
     *
     * @return the value of kaptchas.session_id
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaptchas.session_id
     *
     * @param sessionId the value for kaptchas.session_id
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaptchas.checkcode
     *
     * @return the value of kaptchas.checkcode
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    public String getCheckcode() {
        return checkcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaptchas.checkcode
     *
     * @param checkcode the value for kaptchas.checkcode
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    public void setCheckcode(String checkcode) {
        this.checkcode = checkcode == null ? null : checkcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kaptchas.expire_time
     *
     * @return the value of kaptchas.expire_time
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kaptchas.expire_time
     *
     * @param expireTime the value for kaptchas.expire_time
     *
     * @mbggenerated Sun Jan 22 11:34:25 CST 2017
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }
}